### ISSUE TITLE
How to show legends at the bottom of the chart?

### ISSUE THREAD

**Issue by SAGARSURI** [razerdp/AnimatedPieView#11]
Currently there is no option to show legends below the chart as per my research. Can you tell how can I achieve that ? I didnt find in any of your example also.

**Comment by razerdp** [comment]
I'm sorry,I didn't have a legend feature so far.
Maybe you should implement this function by your self...

I will update this feature in the next release,thanks for your issue.

**Comment by SAGARSURI** [comment]
Waiting for that release eagerly. @razerdp

**Comment by ugoamanoh** [comment]
@razerdp This would be a really good feature, any idea when the next release will be avaialble

**Comment by ugoamanoh** [comment]
I used a GridView for mine but I think it would only for my specific use case
![chart](https://user-images.githubusercontent.com/12151807/42818756-a6c84f0e-89c9-11e8-8ad8-fc13fe7949b0.png)

**Comment by razerdp** [comment]
@ugoamanoh 
@SAGARSURI 

In fact, there are too many legend designs, I can't fit them all.

So,I may provide an interface for you to  create custom legends.


============

PS...

Or I provide a widget to render legends with binding PieView?

**Comment by ugoamanoh** [comment]
Not sure how many different types of designs there are, from memory I can only think of vertical and horizontal styles. I think you should definitely have a default legend then maybe give allow users override with a custom design

**Comment by razerdp** [comment]
hi ~

I'm complete this function

now in version 1.2.5 

you can use `config.legendsWith(viewgroup,pielegendBindListener)` to create or add your custom legendsView which extends BasePieLegendsView
