### ISSUE TITLE
Add icon to labels

### ISSUE THREAD

**Issue by cutiko** [razerdp/AnimatedPieView#12]
Greetings

This is indeed a great library. I would like to request setting icons for every `IPieInfo` optionally. Ideally, it could accept a drawable or a vector. Apps supporting <21 must pass a .png while apps where min is 21 can pass a vector. This way the library doesn't have to deal with supporting vectors on older versions.
The icon would be on the side of the label, depending on the positioning and as the label the color should be the same than in the chart.

![Image Example](https://i.imgur.com/Bz00cfR.png)

Thanks for the awesome work :)

**Comment by razerdp** [comment]
let's do this~

Hope you will be well soon.

**Comment by razerdp** [comment]
Now I have time to do this...

**Comment by razerdp** [comment]
please update to 1.2.4

**Comment by cutiko** [comment]
So icon is a setter `setLabel(Bitmap bm)` thanks! I'm gonna added to the development queue in my project

**Comment by razerdp** [comment]
yep.

`setLabelIcon(Bitmap)` in PieOption.

and you can also decide label's relative position by `setLabelPosition()`.
