### ISSUE TITLE
Unable to click on 2nd Data block when added even number of views

### ISSUE THREAD

**Issue by prasad9323** [razerdp/AnimatedPieView#13]
### 该问题是怎么引起的？
When I add even number of data values in config e.g 2, 4, 6, The pie is unable to click on the 2nd data block. It is not animated on click, and the click event isn't detected even in the SelectListener(). The problem doesn't arise when adding odd numbers of values such as 3,5,7.

### 重现步骤
Create a pieview with all default config, add even numbers of data blocks using addData (i.e calling addData even number of times). Issue will arise when unable to click on 2nd data block. Now try adding only odd number of data (i.e calling addData odd number of times). And everything runs fine.

### 报错信息
No error messege, only unable to detect clicks when clicked on 2nd Data block (2nd value added in config)

**Comment by razerdp** [comment]
I try to create a pie like yours.

However, It performance correctly.

Here is my demo gif.

![](https://i.imgur.com/gX23hD8.gif)

My demo code base from [MainActivity](https://github.com/razerdp/AnimatedPieView/blob/master/app/src/main/java/com/razerdp/demo/MainActivity.java)

```java
        AnimatedPieViewConfig config = new AnimatedPieViewConfig();
        config.startAngle(0.9224089f)
                .addData(new SimplePieInfo(0.11943538617599236, getColor("FF446767")), true)
                .addData(new SimplePieInfo(0.41780274681129415, getColor("FFFFD28C")), true)
                .addData(new SimplePieInfo(0.722165651192247, getColor("FFbb76b4")), true)
                .addData(new SimplePieInfo(0.9184314356136125, getColor("FFFFD28C"), "长文字test"), false)
//                .addData(new SimplePieInfo(0.6028910840057398, getColor("ff2bbc80")), true)
//                .addData(new SimplePieInfo(0.6449620647212785, getColor("ff8be8ff")), true)
//                .addData(new SimplePieInfo(0.058853315195452116, getColor("fffa734d")), true)
//                .addData(new SimplePieInfo(0.6632297717331086, getColor("ff957de0")), true)
//                .addData(new SimplePieInfo(0.8226830459369171, getColor("FF446767")), true)
                .splitAngle(0.9649368f)
                .selectListener(new OnPieSelectListener() {
                    @Override
                    public void onSelectPie(@NonNull IPieInfo pieInfo, boolean isFloatUp) {
                        desc.setText(String.format(Locale.getDefault(),
                                "touch pie >>> {\n  value = %s;\n  color = %d;\n  desc = %s;\n  isFloatUp = %s;\n }",
                                pieInfo.getValue(), pieInfo.getColor(), pieInfo.getDesc(), isFloatUp));
                    }
                })
                .drawText(true)
                .duration(1200)
                .textSize(26)
                .focusAlphaType(AnimatedPieViewConfig.FOCUS_WITH_ALPHA)
                .textGravity(AnimatedPieViewConfig.ABOVE)
                .interpolator(new DecelerateInterpolator());
        mAnimatedPieView.applyConfig(config);
```

**Comment by prasad9323** [comment]
Okay, thanks for the reply, really appreciate your work. I would have sent
you my code, but since it's proprietary to the firm I can't. I'll try to
figure out something. Thanks again.
