### ISSUE TITLE
How do I reduce the margin/padding around the chart

### ISSUE THREAD

**Issue by ugoamanoh** [razerdp/AnimatedPieView#15]
![chart](https://user-images.githubusercontent.com/12151807/42818862-de7b0856-89c9-11e8-8d05-17bf80a38060.png)
How do I reduce the margins in the area around the chart which I have highlighted? It seems a bit excessive and would be nice if we had some control 

I tried calling the `PieManager.setChartContentRect()` to change the margin values but that had no effect

**Comment by razerdp** [comment]
Oh~ my bad...

I'm sorry I haven't written in a document.You can use `pieRadius()` or `pieRadiusRatio()`(this relative to parent's size) in AnimatedPieViewConfig

Usually,the chart use `autoSize`,but there is a little problem and I have fixed it.

I will update today with this issue [#12](https://github.com/razerdp/AnimatedPieView/issues/12) and fix `autoSize()`.
