### ISSUE TITLE
加载饼图时能否设置默认突出显示某个数据块

### ISSUE THREAD

**Issue by heweiquan** [razerdp/AnimatedPieView#16]
### 该问题是怎么引起的？
1.加载显示饼图时不能默认突出显示某个数据块，一定要点击了才能做到这种效果，希望加载饼图时能默认做到如下效果：  
![image](https://user-images.githubusercontent.com/13057762/43620062-77f686a4-9703-11e8-9c50-a69f0f558063.png)  
2.喜欢该库的点击效果，但是又想要MPAndroidChart那种显示效果，块里可以显示label和图例就最好了，希望以后会有这些功能。  
![image](https://user-images.githubusercontent.com/13057762/43623349-4c8e0536-9713-11e8-8998-3f8ad684f468.png)  
![image](https://user-images.githubusercontent.com/13057762/43623370-71d2ddf8-9713-11e8-9cdd-69ba3fc928fa.png)

**Comment by razerdp** [comment]
1 - 可以做到，下个版本优化
2 - 图例在计划中，但是文字显示到块里本来就不是这个库所期望的。。。

**Comment by razerdp** [comment]
@heweiquan 第一个需求点，默认显示已经添加。

具体需要在IPieInfo返回的PieOption里面设置是否默认显示。具体看Demo。

由于Bintray插件仍然未修复针对Gradle>=4.9的上传，因此新版本的库暂时无法发布。
