### ISSUE TITLE
希望添加Label Icon设置大小的api

### ISSUE THREAD

**Issue by VcotyQin** [razerdp/AnimatedPieView#17]
如题

**Comment by razerdp** [comment]
你好，目前的icon是跟随字体大小自身缩放的。

**Comment by razerdp** [comment]
不过可能有些情况下确实需要图标大点，字体小点。
感谢反馈，可以加入到下次的更新中。

**Comment by VcotyQin** [comment]
有时候想用icon作为label

**Comment by razerdp** [comment]
@VcotyQin 你好，具体功能已经添加。

具体需要在IPieInfo返回的PieOption里面设置是icon大小，如果设置了具体的值，则以值为准。具体看Demo。

由于Bintray插件仍然未修复针对Gradle>=4.9的上传，因此新版本的库暂时无法发布。

**Comment by razerdp** [comment]
1.2.5 版本已添加
