### ISSUE TITLE
缺了一块

### ISSUE THREAD

**Issue by VcotyQin** [razerdp/AnimatedPieView#18]
有概率个别数据出现，当焦点在缺处时它又会出现。

**Comment by razerdp** [comment]
比如呢》？有没有相关数据

**Comment by VcotyQin** [comment]
没有，label都没有

**Comment by razerdp** [comment]
额，大概知道什么原因，因为绘制甜甜圈是根据Animation的值去获取对应角度的，如果时间过短，那么单位时间内跨越角度会很大，造成的结果是你所描述的，建议将动画时间调长点

**Comment by VcotyQin** [comment]
还是不行，它开始会闪出来一下，然后瞬间有没了

**Comment by razerdp** [comment]
你贴一下代码吧，我这边好重现，或者加群，交流方便点

**Comment by jackyHuangH** [comment]
我也遇到了这个问题，作者现在解决了吗？

**Comment by Ashion-AS** [comment]
我也遇到这个问题，这个问题很奇怪，我测试发现，当数据是总数7 ，其他4个数如下
        normal = 0;
        notInStorage = 1;
        stockOut = 0;
        notOutOfStock = 6;
        total = 7;
然后依次设置百分比normalPercent=0.0|notInStoragePercent=14.3|stockOutPercent=0.0|notOutOfStockPercent=85.7
就会缺一块不显示……

数据换成  0 0 1 6又正常……

**Comment by Ashion-AS** [comment]
我通过先对数据从小到大排序 再依次 config.addData(）解决……

**Comment by razerdp** [comment]
问题所在应该是跟动画相关。。。。如果没有动画再看看？

**Comment by razerdp** [comment]
pls update to 1.3.0
