### ISSUE TITLE
AnimatedPieView not rendering properly

### ISSUE THREAD

**Issue by Rameshkumarsgp** [razerdp/AnimatedPieView#22]
### 该问题是怎么引起的？
we are using PagerAdapter for rendering the graph. The issue is half the graph is rendering on the screen.
<img width="132" alt="1" src="https://user-images.githubusercontent.com/24287971/52401394-8d6c2e80-2ae7-11e9-925c-44271b6bc51a.PNG">
<img width="134" alt="2" src="https://user-images.githubusercontent.com/24287971/52401398-8e04c500-2ae7-11e9-9765-59d996314d2b.PNG">
<img width="143" alt="3" src="https://user-images.githubusercontent.com/24287971/52401399-8e04c500-2ae7-11e9-86d3-4983ba9bca4e.PNG">

**Comment by razerdp** [comment]
Please provide more details

**Comment by Rameshkumarsgp** [comment]
I am using version 1.2.4 and i added as a project. I am using ViewPager to show the graph with PagerAdapter class.

Activity:
pollList.addAll(obj.getData()); 
viewPager.setOffscreenPageLimit(1);
mCardAdapter = new PollResultsPagerAdapter();

public class PollResultsPagerAdapter extends PagerAdapter 

in the PollResultsPagerAdapter  we are drawing the graph.
I am loading 50  plus data , out of that 30 data will load properly and remaining 20 data wont load or half the graph is loaded.

**Comment by razerdp** [comment]
maybe the remaining 20 data is too small

Can you provide me with a demo or sample data?

**Comment by Rameshkumarsgp** [comment]
I have attached a zip file which contains video of the issues. Have a look at it and let me know anything needed.

[device-2019-02-15-105157.zip](https://github.com/razerdp/AnimatedPieView/files/2867932/device-2019-02-15-105157.zip)

**Comment by razerdp** [comment]
Hi,I've wrote a demo to test your problem.
However, this problem did not come out in the demo.

demo gif:
![demo](https://user-images.githubusercontent.com/11629986/52842389-eb2cf600-3139-11e9-92ff-ba81b8287df6.gif)

[source：ViewPagerActivity](https://github.com/razerdp/AnimatedPieView/blob/master/app/src/main/java/com/razerdp/demo/ViewPagerActivity.java)

**Comment by Rameshkumarsgp** [comment]
ok thanks for your time, let me check from my end.

**Comment by leonidSpiri** [comment]
@Rameshkumarsgp 
Do you solve your problem? I've got the same problem but I've got no idea(

**Comment by Rameshkumarsgp** [comment]
@lenchikspirdonchik Yeah the problem has been fixed.
