### ISSUE TITLE
1.2.5版本，动画显示有问题

### ISSUE THREAD

**Issue by jsntjinjin** [razerdp/AnimatedPieView#25]
1.2.5版本运行，
1、 如果有2个数据，并且有一个大于3/4，会有一个数据会闪一下
2、如果3个数据以上，并且有一个大于3/4，第一个数据会不显示
我降级到1.2.0版本就没这个问题了
另外我使用的是fragment

数据
-------------------
AnimatedPieViewConfig config = new AnimatedPieViewConfig();
        config.addData(new SimplePieInfo(3, getColor(R.color.bg_color4)));
        config.addData(new SimplePieInfo(1, getColor(R.color.bg_color5)));
        config.addData(new SimplePieInfo(83, getColor(R.color.bg_color34)));
        config.splitAngle(1);
        config.duration(1200);
        pieChartView.applyConfig(config).start();

 AnimatedPieViewConfig config = new AnimatedPieViewConfig();
        config.addData(new SimplePieInfo(2, getColor(R.color.bg_color4)));
        config.addData(new SimplePieInfo(43, getColor(R.color.bg_color5)));
        config.splitAngle(1);
        config.duration(1200);
        pieChartView.applyConfig(config).start();

**Comment by razerdp** [comment]
pls update to 1.3.0
