### ISSUE TITLE
Any way to change desc font family / typeface?

### ISSUE THREAD

**Issue by Naxomiun** [razerdp/AnimatedPieView#26]
I've been looking on available methods and there's no way to change typeface. I also checked on library files to see if theres something I can override to change font. No fortune.

Any tips?

**Comment by razerdp** [comment]
AnimatedPieVeiw draws text through drawText(),we can change the font by paint.setTypeface().

I will provide this function for next version

**Comment by razerdp** [comment]
now support that~

However, the new version has not been released yet, and will be released after other issues are completed.
