### ISSUE TITLE
Select PieInfo by tap on its label or icon

### ISSUE THREAD

**Issue by victorlapin** [razerdp/AnimatedPieView#27]
Right now the only way to select PieInfo is to tap on the chart itself. Can you invoke the selectListener by tapping label text and/or icon?

**Comment by razerdp** [comment]
I think this feature can be added to the next version.

**Comment by victorlapin** [comment]
You may as well add option to the config to enable/disable it

**Comment by victorlapin** [comment]
Any news?

**Comment by razerdp** [comment]
@victorlapin 

sry~I have been maintaining [BasePopup](https://github.com/razerdp/BasePopup) recently.So there is no time to maintain this repo.

I will continue to maintain this after the basepopup is released.

**Comment by razerdp** [comment]
not continue.

**Comment by razerdp** [comment]
now support that~

However, the new version has not been released yet, and will be released after other issues are completed.

**Comment by victorlapin** [comment]
Many thanks for your work. Can't donate, because I'm not a WeChat or QQ user...

I'm using it here, if you're interested: https://gitlab.com/victorlapin/usage-stats

**Comment by victorlapin** [comment]
Really sorry to bother you again, description labels are working good, but not icons?

**Comment by razerdp** [comment]
work perfect in demo~
![adsf](https://user-images.githubusercontent.com/11629986/58772911-adbb7e00-85ed-11e9-9e10-5fb2ba231107.gif)

**Comment by victorlapin** [comment]
Okay, let me check once more...

**Comment by victorlapin** [comment]
With this config icons without description labels are still not clickable:
`
AnimatedPieViewConfig()
            .animatePie(true)
            .drawText(true)
            .canTouch(true)
            .strokeMode(true)
            .strokeWidth(8)
            .duration(1000)
            .startAngle(0F)
            .textSize(32F)
            .textMargin(8)
            .splitAngle(0F)
            .interpolator(DecelerateInterpolator())
            .autoSize(true)
            .pieRadiusRatio(1F)
            .animOnTouch(true)
            .focusAlphaType(AnimatedPieViewConfig.FOCUS_WITH_ALPHA_REV)
            .focusAlpha(100)
            .floatShadowRadius(4F)
            .floatExpandSize(4F)
            .typeFae(Typeface.create("sans-serif-condensed", Typeface.NORMAL))
            .selectListener { pieInfo: UsagePieInfo, isFloatUp ->
                if (!pieInfo.appName.isNullOrEmpty() && isFloatUp) {
                    Toast.makeText(context, pieInfo.appName, Toast.LENGTH_SHORT).show()
                }
            }
`

**Comment by razerdp** [comment]
okay~ got this bug

I create a branch to Recurring problem ：[branch:issue_27](https://github.com/razerdp/AnimatedPieView/tree/issue_27)

and I will fix it as soon as possible

**Comment by razerdp** [comment]
pls update to 1.3.0
