### ISSUE TITLE
如果没有数据的话能设置显示一个默认的图表吗？

### ISSUE THREAD

**Issue by dengbing0907** [razerdp/AnimatedPieView#29]

**Comment by dengbing0907** [comment]
比如我有三个项，都是0的情况

**Comment by razerdp** [comment]
没有数据你让我绘制什么呢。。。

**Comment by dengbing0907** [comment]
那线的上面能显示描述+值吗
非常感谢
------------------ 原始邮件 ------------------
发件人: "WeiChaoFeng"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 下午5:11
收件人: "razerdp/AnimatedPieView"<AnimatedPieView@noreply.github.com>;
抄送: "阳光下绚烂的小幸福°"<1175515865@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [razerdp/AnimatedPieView] 如果没有数据的话能设置显示一个默认的图表吗？ (#29)




没有数据你让我绘制什么呢。。。

**Comment by razerdp** [comment]
readme里就有这个需求的gif preview
