### ISSUE TITLE
Color in ring isn't the same than color in label

### ISSUE THREAD

**Issue by ryosoftware** [razerdp/AnimatedPieView#35]
The color in the label isn't the same than color show into the pie.
Not issues in the emulator but in a real device.
Color for 61.08% is `1976D2`
and the color for 38,92% is `64B5F6`
The real colors are the shown in the label

![Sin nombre](https://user-images.githubusercontent.com/31618496/87450856-5c0e6100-c5ff-11ea-9a08-da546d47e71a.png)

**Comment by razerdp** [comment]
I haven't looked at this project because I've been updating basepopup, I'll check this out in the near future

**Comment by razerdp** [comment]
![image](https://user-images.githubusercontent.com/11629986/97832923-01645680-1d0f-11eb-881e-6a09f355bff2.png)

can not reappear

**Comment by razerdp** [comment]
pls update to 1.3.0
