### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by erva** [razerdp/AnimatedPieView#4]

**Comment by razerdp** [comment]
what happen about that?

**Comment by cortinico** [comment]
Can you please provide an English readme as well?

**Comment by razerdp** [comment]
@cortinico 

There is a poor English version in CN README....:)  [link](https://github.com/razerdp/AnimatedPieView/blob/master/README_EN.md)

I'm will update it as soon as possible.... (try to kill the poor english)
