### ISSUE TITLE
字体大小导致的显示问题

### ISSUE THREAD

**Issue by inntechy** [razerdp/AnimatedPieView#5]
setTextSize(48)后，文字与甜甜圈和折线交叉了

```
config.setTextSize(48)
          .setTextLineStrokeWidth(4)// 设置描述文字的指示线宽度
          .setTextLineTransitionLength(50)// 设置描述文字的指示线折角处长度
          .setDirectText(false)
```
最后一个参数改成true也无法解决这个问题

![screenshot_2018-02-01-15-45-14](https://user-images.githubusercontent.com/30460949/35667301-15c0fbc0-0768-11e8-8a8d-e31b0e6c7aa0.png)

**Comment by razerdp** [comment]
@inntechy 收到-V- 下一个版本解决哈

**Comment by abhikommen** [comment]
try this mConfig.setDirectText(true) and set startAngle(0)  // this might work for you

**Comment by razerdp** [comment]
@inntechy @abhishekengineer 

thanks for your solutions

I have fix these problems and I'm going to update to ver-1.2.0（in 24 hours.）

**Comment by abhikommen** [comment]
I m eagerly waiting for next update. I love your piechart. Currently I m working on my app which is using your chart so update as soon as possible so I could finish my work on time.
  
One suggestion : -

public SimplePieInfo(float value, int color, String desc) {
        this.value = value;
        this.color = color;
        this.desc = desc;
    }

why don't you use double in place of float, I think it would increase more possibilities .

**Comment by razerdp** [comment]
@inntechy 你好，请升级到1.2.0

@abhishekengineer yep...I have noticed this problem.I will optimize it in next version.thank you so much for your suggestion :)

There is one point that you should pay attention to:

A lot of methods has been deprecated from version **1.2.0**,although you can use deprecated methods normally,I suggest you to change these methods.

**Comment by abhikommen** [comment]
@razerdp thanks for your kind reply. I love your workkkk.
