### ISSUE TITLE
放在recyclerView上，可以做个不进行动画显示的吗？

### ISSUE THREAD

**Issue by BarretWu** [razerdp/AnimatedPieView#6]

**Comment by BarretWu** [comment]
还有可以做个监听？点击外围自动恢复回原状？浮上的自动恢复

**Comment by razerdp** [comment]
你好，可以的，目前我正在重构这一个控件，年后回来会解决这些问题哦~因为最近也有留意到有人会用在recyclerview上，而且之前项目写的有点乱，最近正在重构
