### ISSUE TITLE
sometime pie chart automatically disappeared from the view.

### ISSUE THREAD

**Issue by abhikommen** [razerdp/AnimatedPieView#8]
sometime the piechart automatically disappeared from the view and then comes automatically back. This scenario keeps take place frequently. Notably, my AnimatePieView is surrounded by a cardview.

**Comment by razerdp** [comment]
Is your piechart used in recyclerview

**Comment by abhikommen** [comment]
no. It still disappearing even when its out of any View Group.

**Comment by razerdp** [comment]
I found that this usually happens when the animation is too short

**Comment by abhikommen** [comment]
so I should increase animation duration ?

**Comment by razerdp** [comment]
@abhishekengineer 

It is exciting that I has fixed this problem

I just released 1.2.1,this version support you to set custom animation Interpolator.

Please update to 1.2.1

**Comment by razerdp** [comment]
BTW,the English comments and documentation are not completed.... 

English Doc Api: [Link](https://github.com/razerdp/AnimatedPieView/blob/master/README_EN.md#api)

However,my English is not good ,can u help me to complete the doc.
