### ISSUE TITLE
文字描述重叠问题

### ISSUE THREAD

**Issue by ihtvr** [razerdp/AnimatedPieView#9]
### 该问题是怎么引起的？
部分比例相对来说会小

### 重现步骤
config
                .addData(new SimplePieInfo(50.9184314356136125, getColor("FFFFD28C"), "长文字test"), false)
                .addData(new SimplePieInfo(0.11943538617599236, getColor("FF446767")), true)
                .addData(new SimplePieInfo(0.11780274681129415, getColor("FFFFD28C")), true)
                .addData(new SimplePieInfo(0.722165651192247, getColor("FFbb76b4")), true)
                .addData(new SimplePieInfo(0.6028910840057398, getColor("ff2bbc80")), true)
                .addData(new SimplePieInfo(0.1249620647212785, getColor("ff8be8ff")), true)
                .addData(new SimplePieInfo(0.158853315195452116, getColor("fffa734d")), true)
                .addData(new SimplePieInfo(0.6632297717331086, getColor("ff957de0")), true)
                .addData(new SimplePieInfo(0.8226830459369171, getColor("FF446767")), true)

**Comment by razerdp** [comment]
说实话，比例太小的情况下，文字重叠似乎没什么好办法解决，毕竟显示空间就那么一点，如果我把数据显示挪到别的地方，可能会显得很乱
